[package]
name = "vidhash-eth21"
version = "0.1.0"
authors = ["G. Queiroz <gabrieljvnq@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-next = "4.3.8"
rustdct = "0.6.0"
transpose = "0.2.1"